---
resources:
- name: hello
  type: git
  source:
    uri: https://github.com/bradex/hello-concourse.git
- name: gist
  type: git
  source:
    uri: git@gist.github.com:9cb14f67f9765c3ae2f70cdda6759915.git
    private_key: {{github-private-key}}
    branch: master

jobs:
- name: job-hello
  public: true
  plan:
  - get: hello
    trigger: true
  - get: gist
  - task: run-hello
    file: hello/hello.yml
  - task: commit-log
    file: hello/commit-log.yml
  - put: gist
    params:
      repository: updated-result

- name: job-show-result # 新規ジョブ
  public: true
  plan:
  - get: hello
  - get: result
    trigger: true
    passed: [ job-hello ]
  - task: show-result
    file: hello/show-result.yml
