---
resources:
- name: hello
  type: git
  source:
    uri: https://github.com/bradex/hello-concourse.git
- name: result
  type: git
  source:
    uri: https://gist.github.com/9cb14f67f9765c3ae2f70cdda6759915.git
    private_key: {{github-private-key}}
    branch: master

jobs:
- name: job-hello
  public: true
  plan:
  - get: hello
    trigger: true
  - get: result
  - task: run-hello
    file: hello/hello.yml
  - task: commit-log
    file: hello/commit-log.yml
  - put: result
    params:
      repository: updated-result
